start: expr
NUM: /[0-9]+/
ADD: "+"
SUB: "-"
MUL: "*"
DIV: "/"
expr: NUM
    | NUM ADD expr
    | NUM SUB expr
    | NUM MUL expr
    | NUM DIV expr

// BOA will ignore this comment due to "// "
// BOA will process comments with "~" after "//"
// Likelihood of a rule -> BOA:non_terminal_rule:alternative_index:likelihood_of_alternative
// Next, BOA will assign a likelihood of 0.005 to "expr: NUM" over the other alternatives of the rule "expr"
//~ BOA:expr:0:0.005
