start: expr
NUM: /[0-9]+/
ADD: "+"
SUB: "-"
MUL: "*"
DIV: "/"
expr: NUM
    | NUM ADD expr
    | NUM SUB expr
    | NUM MUL expr
    | NUM DIV expr

// BOA will ignore this comment due to "// "
// BOA will process comments with "~" after "//"
// Likelihood of a rule -> BOA:non-terminal_rule:index:likelihood_of_rule
// Next BOA rule will assign a likelihood of 0.005 of select "expr: NUM" over the other options of the rule "expr"
//~ BOA:expr:0:0.005
